#!/bin/bash

read file_name
read Public_key

while read -r user_name ip_address
do
    ssh $user_name@ip_address << EOF
    echo "Connected to the remote machine user name: "$user_name" and ip address: "$ip_address""

    cd ~/.ssh

    if [ -n "$(grep "$Public_key" authorized_keys)" ];then
        echo "Given public key already exist in the authorized keys of remote machine, user name: $user_name and ip address: $ip_address "
    else 
        echo "$Public_key" >> authorized_key
        echo "Public key added in authorized.key file of remote machine, user name: $user_name and ip address: $ip_address "
    fi

    echo "Disconnect from the remote machine, user name: $user_name and ip address: $ip_address "
    
    EOF

done < "$file_name"
 


